import * as THREE from "three";
import { hash1 } from "./art.js";

// The volumetric heart is generated by deforming an icosphere along each ray
// until it lands on the surface of a star-shaped implicit heart field. This
// produces a smooth, closed three-dimensional heart with real depth from every
// angle — the two lobes, the cleft, and the lower point.
//
// Implicit field (classic canonical heart, f < 0 inside):
//   f(x,y,z) = ( x^2 + (9/4) y^2 + z^2 - 1 )^3  - x^2 z^3  - (9/80) y^2 z^3
// In this frame the lobes/cleft lie along +/-x and the point reaches toward -z.

const DATA = { x: 0, y: 0, z: 0 }; // scratch

function heartField(x, y, z) {
  const a = x * x + 2.25 * y * y + z * z - 1;
  return a * a * a - x * x * z * z * z - 0.1125 * y * y * z * z * z;
}

function surfaceRadius(dx, dy, dz) {
  const len = Math.hypot(dx, dy, dz) || 1;
  dx /= len;
  dy /= len;
  dz /= len;
  let lo = 0.001;
  let hi = 2.4;
  for (let i = 0; i < 60; i++) {
    const mid = (lo + hi) * 0.5;
    if (heartField(dx * mid, dy * mid, dz * mid) < 0) lo = mid;
    else hi = mid;
  }
  return (lo + hi) * 0.5;
}

/**
 * Builds the heart geometry.
 * @param {number} detail icosphere subdivision (3..6). Higher = finer facets.
 * @param {number} radius target max half-extent.
 * @returns {{geometry: THREE.BufferGeometry, points: Float32Array}}
 */
export function createHeartGeometry(detail = 4, radius = 1) {
  const source = new THREE.IcosahedronGeometry(1, detail);
  const pos = source.attributes.position;
  const count = pos.count;

  const deformed = new Float32Array(count * 3);
  let maxAbs = 0;
  let maxX = 0,
    minX = 0,
    maxY = 0,
    minY = 0,
    maxZ = 0,
    minZ = 0;

  for (let i = 0; i < count; i++) {
    const x = pos.getX(i);
    const y = pos.getY(i);
    const z = pos.getZ(i);
    const r = surfaceRadius(x, y, z);
    const dx = x * r;
    const dy = y * r;
    const dz = z * r;

    // Map implicit frame -> world: lobes along X, depth along Z, point along -Y.
    const wx = dx;
    const wy = dz;
    const wz = dy;

    deformed[i * 3 + 0] = wx;
    deformed[i * 3 + 1] = wy;
    deformed[i * 3 + 2] = wz;

    maxAbs = Math.max(maxAbs, Math.abs(wx), Math.abs(wy), Math.abs(wz));
    maxX = Math.max(maxX, wx); minX = Math.min(minX, wx);
    maxY = Math.max(maxY, wy); minY = Math.min(minY, wy);
    maxZ = Math.max(maxZ, wz); minZ = Math.min(minZ, wz);
  }

  // Normalize so the largest half-extent equals `radius`.
  const scale = radius / maxAbs;
  for (let i = 0; i < count * 3; i++) deformed[i] *= scale;

  // Slight per-vertex "imperfection" jitter yields a crystalline, hand-cut feel
  // without breaking the silhouette. Keep the tip of the heart cleaner.
  const jittered = deformed.slice();
  for (let i = 0; i < count; i++) {
    const k = i * 3;
    const j = (hash1(i) - 0.5) * 0.012 * radius;
    jittered[k + 0] += j;
    jittered[k + 1] += j * (1 - Math.abs(deformed[k + 1]) * 0.6);
    jittered[k + 2] += j * 0.8;
  }

  const geometry = new THREE.BufferGeometry();
  // The (x,y,z) -> (x,z,y) remap is a reflection (det = -1), which reverses the
  // winding and leaves every face pointing inward. Rebuild the index order so
  // faces point outward again; flat shading then produces correct surface normals.
  const flipped = jittered.slice();
  for (let i = 0; i < count; i += 3) {
    const b = (i + 1) * 3;
    const c = (i + 2) * 3;
    for (let k = 0; k < 3; k++) {
      const tmp = flipped[b + k];
      flipped[b + k] = flipped[c + k];
      flipped[c + k] = tmp;
    }
  }
  // Non-indexed so the flat-shaded facets read cleanly across the whole surface.
  geometry.setAttribute("position", new THREE.BufferAttribute(flipped, 3));

  // Per-face construction order (tip -> lobes, 0..1) so the shell can build
  // itself as a sequential wave of facets, growing from the tip upward.
  const yRange = Math.max(1e-5, maxY - minY);
  const orderAttr = new Float32Array(count);
  for (let i = 0; i < count; i += 3) {
    const cy = (flipped[i * 3 + 1] + flipped[(i + 1) * 3 + 1] + flipped[(i + 2) * 3 + 1]) / 3;
    const o = Math.min(1, Math.max(0.16, (cy - minY) / yRange));
    orderAttr[i] = o;
    orderAttr[i + 1] = o;
    orderAttr[i + 2] = o;
  }
  geometry.setAttribute("aOrder", new THREE.BufferAttribute(orderAttr, 1));
  geometry.computeBoundingBox();
  geometry.computeBoundingSphere();

  return { geometry, points: flipped, bounds: { maxX, maxY, maxZ, minX, minY, minZ, scale } };
}
